### ISSUE TITLE
Is Packagekit support really needed in Gnome Software on an immutable distro?

### ISSUE THREAD

**Issue by user1-github** [arkanelinux/pkgbuild#1]
Hi,
I hope this is the right place to ask this.

I'm a big fan of immutable distros and previously I tried Fedora Silverblue and then OpenSUSE Aeon. I only found out about Arkane Linux a week ago. It seemed interesting (I was surprised I didn't know about it earlier), installed it the next day and now it's my favorite immutable distro. So you gained a new user :)

So far everything works perfectly, but the only thing that surprised me a bit is that Gnome Software is patched to support Packagekit. Is it really needed for something on an immutable distro? I guess that's also the reason Gnome Software is a bit outdated compared to all other Gnome components (it's currently on version 46.0, while the latest one is 46.3). Gnome Software 46.0 has a bug where some Flathub app icons are invisible. It is fixed in 46.1.

**Comment by dennis1248** [comment]
gnome-software being patched with packagekit support is tiny bit of legacy. There used to also be a mutable version where the packagekit support was used.

The mutable version I dropped a few months ago from the download page, reason being that it was running behind in maintenance, but I kept the package around with the plan to eventually restore the mutable version of the OS.

I have since decided to fully focus on the immutable version instead.

I dropped the package in https://github.com/arkanelinux/pkgbuild/commit/aade2c42a6d43663acb3eb9f652c6c600f1fb08f

I will push an image update right away also.
